name: contract_kit
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies:
  http: ^0.13.3
  logger: ^1.0.0
  web3dart: ^2.1.4
